config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root "homes#top"
    get 'about' => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => "customers#show"
    get 'customers/information/edit' => "customers#edit"
    patch 'customers/information' => "customers#update"
    get 'customers/confirm'
    patch 'customers/withdraw'
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/finish'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'
    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]
    get "searches" => "searches#search"
  end

  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "index/:id" => "orders#index"
    resources :order_items, only: [:update]
    get "searches" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :cart_items, dependent: :destroy
  has_one_attached :item_image
  belongs_to :genre

  validates :item_name, presence: true, uniqueness: true
  validates :item_body, presence: true
  validates :none_taxed_price, presence: true

  def get_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpeg")
      item_image.attach(io: File.open(file_path), filename: "default-image.jpeg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_fill: [width, height]).processed
  end

  # 税込価格を取得
  def taxed_price
    tax = 1.1
    (none_taxed_price * tax).floor
  end

  def self.search_for(content)
    Item.where("item_name LIKE?", "#{content}")
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
     if @item.save
      flash[:notice] = "商品の登録に成功しました"
      redirect_to admin_item_path(@item)
     else
      flash[:notice] = "商品の登録に失敗しました"
      render :new
     end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品の更新に成功しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品の更新に失敗しました"
      render :edit
    end
  end

  private
  
  def item_params
    params.require(:item).permit(:item_image, :item_name, :item_body, :genre_id, :none_taxed_price, :sale_status)
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_sale_status.html.erb
<% if item.sale_status == true %>
  <span class="text-success">販売中</span>
<% else %>
  <span class="text-secondary">販売停止中</span>
<% end %>

app/views/admin/items/edit.html.erb
<div class="row mt-3">
  <div class="row col-12">
    <h4 class="mb-3">商品編集</h4>
  </div>
  <%= render "layouts/errors", obj: @item %>
  <div class="row col-12">
    <div class="col-3"></div>
    <%= form_with model: @item, url: admin_item_path(@item), class: "col-5 mb-5" do |f| %>
      <div class="form-group row">
        <%= f.label :item_image, "商品画像", class: "col-4" %>
        <%= f.file_field :item_image, accept: "image/*", class: "col-8 pl-0" %>
      </div>
      <div class="form-group row">
        <%= f.label :item_name, "商品名", class: "col-4" %>
        <%= f.text_field :item_name, placeholder: "商品名", class: "col-8" %>
      </div>
      <div class="form-group row">
        <%= f.label :item_body, "商品説明", class: "col-4" %>
        <%= f.text_area :item_body, rows: "5", placeholder: "ここに説明文を記述します", class: "col-8" %>
      </div>
      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-4" %>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name), {}, {class: "col-8 select"} %>
      </div>
      <div class="form-group row">
        <%= f.label :none_taxed_price, "税抜価格", class: "col-4" %>
        <%= f.text_field :none_taxed_price, placeholder: "1000", class: "col-7" %>
        <span class="d-flex align-items-center ml-1">円</span>
      </div>
      <div class="form-group row">
        <%= f.label :sale_status, "販売ステータス", class: "col-4" %>
        <%= f.radio_button :sale_status, true, class: "mr-1" %>
        <%= f.label :sale_status, "販売中", class: "mr-5 d-flex align-items-center mb-0" %>
        <%= f.radio_button :sale_status, false, class: "mr-1" %>
        <%= f.label :sale_status, "販売停止中", class: "mr-5 d-flex align-items-center mb-0" %>
      </div>
      <div class="form-group text-center">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="row mt-3">
  <div class="col-lg-12 mx-auto">
    <div class="row">
      <h4 class="col-11 mb-3">商品一覧</h4>
      <%= link_to new_admin_item_path do %>
        <div class="new-btn">
          <i class="fas fa-plus"></i>
        </div>
      <% end %>
    </div>
    <table class="table table-hover table-borderless">
      <thead>
        <tr class="table-active">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.item_name, admin_item_path(item), class: "text-dark text-decoration-none  border-bottom border-dark" %></td>
            <td><%= number_with_delimiter item.none_taxed_price %></td>
            <td><%= item.genre.genre_name %></td>
            <th><%= render "sale_status", item: item %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="row mt-3">
  <div class="row col-12">
    <h4 class="mb-3">商品新規登録</h4>
  </div>
  <%= render "layouts/errors", obj: @item %>
  <div class="row col-12">
    <div class="col-3"></div>
    <%= form_with model: @item, url: admin_items_path, class: "col-5 mb-5" do |f| %>
      <div class="form-group row">
        <%= f.label :item_image, "商品画像", class: "col-4" %>
        <%= f.file_field :item_image, accept: "image/*", class: "col-8 pl-0" %>
      </div>
      <div class="form-group row">
        <%= f.label :item_name, "商品名", class: "col-4" %>
        <%= f.text_field :item_name, placeholder: "商品名", class: "col-8" %>
      </div>
      <div class="form-group row">
        <%= f.label :item_body, "商品説明", class: "col-4" %>
        <%= f.text_area :item_body, rows: "5", placeholder: "ここに説明文を記述します", class: "col-8" %>
      </div>
      <div class="form-group row">
        <%= f.label :genre_id, "ジャンル", class: "col-4" %>
        <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name), {include_blank: '選択してください'}, {class: "col-8 select"} %>
      </div>
      <div class="form-group row">
        <%= f.label :none_taxed_price, "税抜価格", class: "col-4" %>
        <%= f.text_field :none_taxed_price, placeholder: "1000", class: "col-7" %>
        <span class="d-flex align-items-center ml-1">円</span>
      </div>
      <div class="form-group row">
        <%= f.label :sale_status, "販売ステータス", class: "col-4" %>
        <%= f.radio_button :sale_status, true, class: "mr-1" %>
        <%= f.label :sale_status, "販売中", class: "mr-5 d-flex align-items-center mb-0" %>
        <%= f.radio_button :sale_status, false, class: "mr-1" %>
        <%= f.label :sale_status, "販売停止中", class: "mr-5 d-flex align-items-center mb-0" %>
      </div>
      <div class="form-group text-center">
        <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="row d-flex mt-3">
  <h4 class="mb-3">商品詳細</h4>
  <div class="col-12 d-flex justify-content-left">
    <div>
      <%= image_tag @item.get_image(300, 200) %>
    </div>
    <table class="col-6 ml-5">
      <thead></thead>
      <tbody>
        <tr>
          <th class="col-3 pl-0">商品名</th>
          <th><%= @item.item_name %></th>
        </tr>
        <tr>
          <th class="d-flex pl-0 align-items-start">商品説名</th>
          <th><%= @item.item_body %></th>
        </tr>
        <tr>
          <th class="col-3 pl-0">ジャンル</th>
          <th><%= @item.genre.genre_name %></th>
        </tr>
        <tr>
          <th class="col-3 pl-0">
            税込価格<br>
            (税抜価格)
          </th>
          <th>
            <%= number_with_delimiter @item.taxed_price %>
            （<%= number_with_delimiter @item.none_taxed_price %>）円
          </th>
        </tr>
        <tr>
          <th class="col-3 pl-0">販売ステータス</th>
          <th><%= render "sale_status", item: @item %></th>
        </tr>
        <tr>
          <th></th>
          <th><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-lg btn-success mt-3" %></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>