config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root "homes#top"
    get 'about' => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => "customers#show"
    get 'customers/information/edit' => "customers#edit"
    patch 'customers/information' => "customers#update"
    get 'customers/confirm'
    patch 'customers/withdraw'
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/finish'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'
    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]
    get "searches" => "searches#search"
  end

  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "index/:id" => "orders#index"
    resources :order_items, only: [:update]
    get "searches" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  # 小計を取得
  def item_total_price
    amount * item.taxed_price
  end

  def amount_options
    options = []
    (self.amount + 11).times do |count|
      options << [count, count]
    end
    return options
  end

  def self.total_price(customer)
    CartItem.where(customer_id: customer.id).inject(0){|sum, cart_item| sum + cart_item.item_total_price}
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses
  has_many :orders
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: :true, format: {with:/\A[一-龥ぁ-ん]/,message: "は、漢字・ひらがなのどちらかで入力して下さい"}
  validates :first_name, presence: :true, format: {with:/\A[一-龥ぁ-ん]/, message: "は、漢字・ひらがなのどちらかで入力して下さい"}
  validates :last_name_kana, presence: :true, format: {with:/\A[ァ-ヶー－]+\z/, message: "は、全角カタカナのみで入力して下さい"}
  validates :first_name_kana, presence: :true, format: {with:/\A[ァ-ヶー－]+\z/, message: "は、全角カタカナのみで入力して下さい"}
  validates :postcode, presence: :ture, format: {with:/\A\d{7}\z/, message: "は、半角数字で入力してください"}
  validates :address, presence: :ture
  validates :phone_number, presence: :ture, format:{ with:/\A\d{10,11}\z/, message: "は、半角数字で入力してください"}
  validates :customer_status, inclusion: {in: [true, false]}

 #退会済みユーザーの識別
 def active_for_authentication?
  super && (self.customer_status == false)
 end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :genre_name, presence: true, uniqueness: true

  def self.search_for(content)
    genres = Genre.where("genre_name LIKE?", "#{content}")
    genres.inject(init = []){|result, genre| result + genre.items}
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :cart_items, dependent: :destroy
  has_one_attached :item_image
  belongs_to :genre

  validates :item_name, presence: true, uniqueness: true
  validates :item_body, presence: true
  validates :none_taxed_price, presence: true

  def get_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join("app/assets/images/default-image.jpeg")
      item_image.attach(io: File.open(file_path), filename: "default-image.jpeg", content_type: "image/jpeg")
    end
    item_image.variant(resize_to_fill: [width, height]).processed
  end

  # 税込価格を取得
  def taxed_price
    tax = 1.1
    (none_taxed_price * tax).floor
  end

  def self.search_for(content)
    Item.where("item_name LIKE?", "#{content}")
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer

  enum payment: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_for_payment: 0, payment_comfirmation: 1, producting: 2, shipping_preparation: 3, shipped: 4 }

  #小計
  def total_items
    order_items.nochange_taxed_price * order_items.amount
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum manufacture_status: { impossible_to_manufacture: 0, waiting_for_manufacture: 1, manufacturing: 2, manufactured: 3 }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: :ture, format: {with:/\A\d{7}\z/, message: "は半角数字で入力してください"}
  validates :address, presence: :ture
  validates :address_name, presence: :true

  def address_display
    "〒" + postcode + " " + address + " " + address_name
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"

  def top
    @orders = Order.page(params[:page]).order(created_at: :desc)
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"
  
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
     if @item.save
      flash[:notice] = "商品の登録に成功しました"
      redirect_to admin_item_path(@item)
     else
      flash[:notice] = "商品の登録に失敗しました"
      render :new
     end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品の更新に成功しました"
      redirect_to admin_item_path(@item)
    else
      flash[:notice] = "商品の更新に失敗しました"
      render :edit
    end
  end

  private
  
  def item_params
    params.require(:item).permit(:item_image, :item_name, :item_body, :genre_id, :none_taxed_price, :sale_status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
       <%= link_to admin_root_path do %>
         <%= image_tag 'nagano_cake_logo.png', size: '150x90', class: "navbar-brand" %>
       <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item btn">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
            </li>
          <% else %>
            <li class="nav-item btn">
              <%= link_to "About", about_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-light' %>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item ml-auto pr-3">
            <%= render "admin/searches/form" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %> 件のエラーが発生しました。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class='container py-3'>
  	<div class='row my-auto d-flex justify-content-center'>
    	<p>©NaganoCake</p>
    </div>
  </div>
</footer>

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="about_bg">
    <div class="filter-about">
      <%= render 'public/header' %>
      <main>
        <p id="notice"><%= notice %></p>
        <div class='container'>
          <div class='row'>
            <div class='col-12'>
              <%= yield %>
            </div>
          </div>
        </div>
      </main>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/header' %>
    <main>
      <p id="notice"><%= notice %></p>
      <div class='container'>
        <div class='row'>
          <div class='col-12'>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'public/header' %>
    <main>
      <p id="notice"><%= notice %></p>
      <div class='container'>
        <div class='row'>
          <div class='col-12'>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>