config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root "homes#top"
    get 'about' => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => "customers#show"
    get 'customers/information/edit' => "customers#edit"
    patch 'customers/information' => "customers#update"
    get 'customers/confirm'
    patch 'customers/withdraw'
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/finish'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'
    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]
    get "searches" => "searches#search"
  end

  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "index/:id" => "orders#index"
    resources :order_items, only: [:update]
    get "searches" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses
  has_many :orders
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: :true, format: {with:/\A[一-龥ぁ-ん]/,message: "は、漢字・ひらがなのどちらかで入力して下さい"}
  validates :first_name, presence: :true, format: {with:/\A[一-龥ぁ-ん]/, message: "は、漢字・ひらがなのどちらかで入力して下さい"}
  validates :last_name_kana, presence: :true, format: {with:/\A[ァ-ヶー－]+\z/, message: "は、全角カタカナのみで入力して下さい"}
  validates :first_name_kana, presence: :true, format: {with:/\A[ァ-ヶー－]+\z/, message: "は、全角カタカナのみで入力して下さい"}
  validates :postcode, presence: :ture, format: {with:/\A\d{7}\z/, message: "は、半角数字で入力してください"}
  validates :address, presence: :ture
  validates :phone_number, presence: :ture, format:{ with:/\A\d{10,11}\z/, message: "は、半角数字で入力してください"}
  validates :customer_status, inclusion: {in: [true, false]}

 #退会済みユーザーの識別
 def active_for_authentication?
  super && (self.customer_status == false)
 end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(
      :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :email, :customer_status
    )
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_customer_status.html.erb
<% if customer.customer_status == false %>
  <span class="text-success">有効</span>
<% else %>
  <span class="text-secondary">退会</span>
<% end %>

app/views/admin/customers/_edit.html.erb
<%= form_with model: customer, url: admin_customer_path, method: :patch, local: false do |f| %>
  <%= render "layouts/errors", obj: customer %>
  <div class="mb-3 field">
    <%= f.label :customer, "会員ID", class: "col-2" %>
    <%= customer.id %>
  </div>
  <div class="mb-3 field">
    <%= f.label :last_name, "氏名", class: "col-2" %>
    <%= f.text_field :last_name, autofocus: true, class: "col-3" %>
    <%= f.text_field :first_name, class: "col-3" %>
  </div>
  <div class="mb-3 field">
    <%= f.label :last_name_kana, "フリガナ", class: "col-2" %>
    <%= f.text_field :last_name_kana, class: "col-3" %>
    <%= f.text_field :first_name_kana, class: "col-3" %>
  </div>
  <div class="mb-3 field">
    <%= f.label :postcode, "郵便番号", class: "col-2" %>
    <%= f.text_field :postcode, class: "col-3" %>
   </div>
   <div class="mb-3 field">
     <%= f.label :address, "住所", class: "col-2" %>
     <%= f.text_field :address, class: "col-8" %>
   </div>
   <div class="mb-3 field">
     <%= f.label :phone_number, "電話番号", class: "col-2" %>
     <%= f.text_field :phone_number, class: "col-3" %>
   </div>
   <div class="mb-3 field">
     <%= f.label :email, "メールアドレス", class: "col-2" %>
     <%= f.text_field :email, class: "col-3" %>
   </div>
   <div class="mb-3 field">
     <%= f.label :customer_status, "会員ステータス", class: "col-2" %>
     <%= f.radio_button :customer_status, :false, checked: true %>
     <%= f.label :customer_status, "有効" %>
     <%= f.radio_button :customer_status, :true, class: "ml-3" %>
     <%= f.label :customer_status, "退会" %>
   </div>
   <%= f.submit "変更を保存", class: "btn btn-success btn-md" %>
 <% end %>

app/views/admin/customers/edit.html.erb
<div class="row mt-3">
  <div class="col-12 mx-auto">
    <h4 class="mb-3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    <div id="edit">
      <%= render "edit", customer: @customer %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="row mt-3">
  <div class="col-lg-12 mx-auto">
    <h4 class="mb-3">会員一覧</h4>
    <table class="table table-bordered">
      <thead class="table-active">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer), class: "text-dark border-bottom border-dark text-decoration-none" do %>
                <%= customer.last_name %><%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td><%= render "admin/customers/customer_status", customer: customer %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="row mt-3">
  <div class="col-lg-12 mx-auto">
    <h4 class="mb-3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row">会員ID</th>
          <td><%= @customer.id%></td>
        </tr>
        <tr>
          <th scope="row">氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %></td>
        </tr>
        <tr>
          <th scope="row">フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th scope="row">郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th scope="row">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th scope="row">電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th scope="row">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th scope="row">会員ステータス</th>
          <td><%= render "admin/customers/customer_status", customer: @customer %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success btn-md" %></td>
          <td><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary btn-md" %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/update.js.erb
$('#edit').html("<%= j(render 'edit', customer: @customer ) %>")