config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root "homes#top"
    get 'about' => "homes#about"
    resources :items, only: [:index, :show]
    get 'customers/my_page' => "customers#show"
    get 'customers/information/edit' => "customers#edit"
    patch 'customers/information' => "customers#update"
    get 'customers/confirm'
    patch 'customers/withdraw'
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:create, :index, :update, :destroy]
    get 'orders/finish'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm'
    resources :shipping_addresses, only: [:create, :index, :edit, :update, :destroy]
    get "searches" => "searches#search"
  end

  namespace :admin do
    root "homes#top"
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    get "index/:id" => "orders#index"
    resources :order_items, only: [:update]
    get "searches" => "searches#search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer

  enum payment: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_for_payment: 0, payment_comfirmation: 1, producting: 2, shipping_preparation: 3, shipped: 4 }

  #小計
  def total_items
    order_items.nochange_taxed_price * order_items.amount
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"

  def index
    @customer = Customer.find(params[:id])
    @orders   = @customer.orders.page(params[:page]).order(created_at: :desc)
  end

  def show
    @order       = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    @order       = Order.find(params[:id])
    @order_items = @order.order_items
    @order.update(order_params)
    if  @order.order_status == "payment_comfirmation"
      @order.order_items.update_all(manufacture_status: "waiting_for_manufacture")
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_manufacture_status.html.erb
<%= form_with model: order_item, url: admin_order_item_path(order_item), method: :patch, local: false do |f| %>
  <%= f.select :manufacture_status, OrderItem.manufacture_statuses.keys.map {|k| [I18n.t("enums.order_item.manufacture_status.#{k}"), k]} %>
  </td>
  <td><%= f.submit "更新", class: "btn btn-sm btn-success" %></td>
<% end %>

app/views/admin/orders/_order_item_table.html.erb
<% order_items.each do |order_item| %>
  <tr>
    <td><%= order_item.item.item_name %></td>
    <td><%= order_item.nochange_taxed_price %></td>
    <td><%= order_item.amount %></td>
    <td><%= number_with_delimiter(order_item.nochange_taxed_price * order_item.amount) %></td>
    <td class="manufacture_status_<%= order_item.id %>">
      <%= render "admin/order_items/manufacture_status", order_item: order_item %>
    </td>
  </tr>
<% end %>

app/views/admin/orders/_order_status.html.erb
<%= form_with model: order, url: admin_order_path(order), method: :patch, local: false do |f| %>
  <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, {}, {class: 'form select'} %>
  <%= f.submit "更新", class: "btn btn-sm btn-success ml-3" %>
<% end %>

app/views/admin/orders/index.html.erb
<div class="row mt-3">
  <div class="col-12">
    <h4 class="mb-3"><strong><%= @customer.last_name + @customer.first_name %></strong> さんの<strong>注文履歴</strong></h4>
    <table class="table table-hover">
      <thead class="table-active">
        <tr>
          <th></th>
          <th>購入日時</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td></td>
            <td><%= order.created_at.strftime("%Y/%m/%d/ %H:%M:%S") %></td>
            <td>
              <% total_amount = 0 %>
              <% order.order_items.each do |order_items| %>
                <% amounts = order_items.amount %>
                <% total_amount += amounts %>
              <% end %>
              <%= total_amount %>
            </td>
            <td><%= order.order_status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex justify-content-center">
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="row mt-3">
  <h4 class="mb-3">注文履歴詳細</h4>
  <table class="table table-borderless mb-3">
    <tr>
      <th class="col-2"><strong>購入者</strong></th>
      <td><%= @order.customer.last_name + @order.customer.first_name %></td>
    </tr>
    <tr>
      <th><strong>注文日</strong></th>
      <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th><strong>配送先</strong></th>
      <td>
        〒<%= @order.order_postcode%> <%=@order.order_address %><br>
        <%= @order.order_address_name %>
      </td>
    </tr>
    <tr>
      <th><strong>支払方法</strong></th>
      <td><%= @order.payment_i18n %></td>
    </tr>
    <tr>
      <th><strong>注文ステータス</strong></th>
      <td id="order_status">
        <%= render "order_status", order: @order %>
      </td>
    </tr>
  </table>
</div>
<div class="row mt-3">
  <table class="table col-8">
    <thead class="table-active">
      <tr>
        <th><strong>商品名</strong></th>
        <th><strong>単価(税込)</strong></th>
        <th><strong>数量</strong></th>
        <th><strong>小計</strong></th>
        <th><strong>製作ステータス</strong></th>
      </tr>
    </thead>
    <tbody class="manufacture_status">
      <%= render "order_item_table", order_items: @order_items %>
    </tbody>
  </table>
  <div class="col-1"></div>
  <table class="table-borderless col-2">
    <tr>
      <th><strong>商品合計</strong></th>
      <td><%= number_with_delimiter(@order.billing_price - @order.postage).to_s + "円" %></td>
    </tr>
    <tr>
      <th><strong>送料</strong></th>
      <td><%= number_with_delimiter(@order.postage.to_s) + "円" %></td>
    </tr>
    <tr>
      <th><strong>請求金額合計</strong></th>
      <td><%= number_with_delimiter(@order.billing_price).to_s + "円" %></td>
    </tr>
  </table>
</div>

app/views/admin/orders/update.js.erb
$('#order_status').html("<%= j(render "order_status", order: @order) %>")
$('.manufacture_status').html("<%= j(render "order_item_table", order_items: @order_items) %>")